lang: pt-br
title: Dudu's Blog
email: eduardokmesiano@gmail.com
description: >-
  Blog de teste. Para aprender Jekyll e me motivar a começar a escrever.
baseurl: "/blog"
url: "https://dudukling.github.io/"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# Defaults:
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Eduardo Kling Mesiano"

