lang: pt-br
title: I'm Not That Creative Blog
email: eduardokmesiano@gmail.com
description: >-
  I'm Not That Creative is my test blog, to learn Jekyll.
baseurl: "/blog"
url: "https://dudukling.github.io/"
github_username:  dudukling

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# Defaults:
defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
      author: "Eduardo Kling Mesiano"

