lang: pt-br
title: Dudu's Blog
email: eduardokmesiano@gmail.com
description: >-
  This blog is my test blog, to learn Jekyll and share some info.
baseurl: "/blog"
url: "https://dudukling.github.io/"
github_username:  dudukling

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# Defaults:
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Eduardo Kling Mesiano"

